# Fluxless gateway Deployment Module
#
# Installs Pipeline Control gateway in FLUXLESS mode. Two Helm charts installed
# sequentially:
#   1. newrelic/agent-control-deployment — installs Agent Control (namespace-scoped)
#   2. newrelic/pipeline-control-gateway — installs the gateway (Deployment or DaemonSet)
#
# Equivalent CLI commands (this module runs them via Terraform):
#   helm upgrade --install agent-control-deployment newrelic/agent-control-deployment \
#     -n newrelic --create-namespace --values <agent_control_values_file>
#
#   helm upgrade --install newrelic-pcg newrelic/pipeline-control-gateway \
#     -n newrelic --create-namespace --values <pcg_values_file>
#
# Contrast with 5-pcg/flux: that module uses agent-control-BOOTSTRAP
# (different chart) which installs Flux which installs the gateway. Requires cluster-admin.
# Fluxless is namespace-scoped, no Flux, no cluster-admin.
#
# INTERFACE MATCHES 5-pcg/flux for out-of-cluster ingress + Route53. Both
# modules are drop-in replacements — pick on RBAC scope, everything
# downstream (ALB, cert-manager, NGINX, Kong) works identically.

# ─────────────────────────────────────────────────────────────────────────────
# Data sources — cluster discovery
# ─────────────────────────────────────────────────────────────────────────────

data "aws_eks_cluster" "selected" {
  name = var.cluster_name
}

data "aws_eks_cluster_auth" "selected" {
  name = var.cluster_name
}

locals {
  common_labels = {
    "app.kubernetes.io/managed-by" = "terraform"
    "app.kubernetes.io/part-of"    = "pipeline-control-gateway"
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Namespace
# ─────────────────────────────────────────────────────────────────────────────
# Fluxless is namespace-scoped: both charts install into pcg_namespace (default
# "newrelic"). We create it if it doesn't exist. An earlier module (4.3-pcg-certificate
# for intra-cluster, 4.2-out-of-cluster-tls for out-of-cluster) may have already
# created it — create_pcg_namespace flag defaults to false so this module doesn't
# collide.

resource "kubernetes_namespace_v1" "pcg" {
  count = var.create_pcg_namespace ? 1 : 0

  metadata {
    name = var.pcg_namespace
    labels = merge(local.common_labels, {
      name = var.pcg_namespace
    })
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Chart 1: Agent Control (agent-control-deployment)
# ─────────────────────────────────────────────────────────────────────────────
# Namespace-scoped install. No Flux. No cluster-admin RBAC.
# The values.yaml file is generated by the New Relic install wizard.

resource "helm_release" "agent_control" {
  name       = "agent-control-deployment"
  repository = "https://helm-charts.newrelic.com"
  chart      = "agent-control-deployment"
  version    = var.agent_control_chart_version != "" ? var.agent_control_chart_version : null
  namespace  = var.pcg_namespace

  # Skip create_namespace flag — we handle namespace creation above via
  # kubernetes_namespace_v1 (conditional on var.create_pcg_namespace).
  create_namespace = false

  values = [file(var.agent_control_values_file)]

  timeout = 600
  wait    = true

  depends_on = [kubernetes_namespace_v1.pcg]
}

# Small wait so Agent Control's pods are Ready before gateway chart references them.
# Not strictly required by the CLI equivalent — Helm's `wait = true` above does
# most of it — but adds a safety margin in slower clusters.
resource "time_sleep" "wait_for_agent_control" {
  depends_on      = [helm_release.agent_control]
  create_duration = var.agent_control_wait_duration
}

# ─────────────────────────────────────────────────────────────────────────────
# Chart 2: The gateway itself (pipeline-control-gateway)
# ─────────────────────────────────────────────────────────────────────────────
# The values.yaml file controls kind: Deployment OR DaemonSet. Same Helm command
# either way — no Terraform-level branching needed. Deployment = default (2-N
# replicas, HPA-friendly). DaemonSet = one pod per node (Mode 2 below, which
# uses internalTrafficPolicy: Local for local-node routing).

resource "helm_release" "pcg" {
  name       = "newrelic-pcg"
  repository = "https://helm-charts.newrelic.com"
  chart      = "pipeline-control-gateway"
  version    = var.pcg_chart_version != "" ? var.pcg_chart_version : null
  namespace  = var.pcg_namespace

  create_namespace = false

  values = [file(var.pcg_values_file)]

  timeout = 600
  wait    = true

  depends_on = [time_sleep.wait_for_agent_control]
}

# Brief wait so the gateway's Service is registered before downstream Ingress references it.
resource "time_sleep" "wait_for_pcg" {
  depends_on      = [helm_release.pcg]
  create_duration = var.pcg_wait_duration
}

# ─────────────────────────────────────────────────────────────────────────────
# Out-of-cluster — ALB Ingress + Route53 alias record
#
# IDENTICAL block to the out-of-cluster section in 5-pcg/flux/main.tf. Same
# annotations, same routing paths, same time_sleep triggers, same alias record.
# Intra-cluster users leave create_alb_ingress = false and this section is skipped.
# ─────────────────────────────────────────────────────────────────────────────

resource "kubernetes_ingress_v1" "pcg_alb" {
  count = var.create_alb_ingress ? 1 : 0

  metadata {
    name      = "pcg-alb"
    namespace = var.pcg_namespace
    labels    = local.common_labels

    annotations = {
      # ALB scheme — "internal" for private-only (out-of-cluster default)
      "alb.ingress.kubernetes.io/scheme" = var.alb_scheme

      # target-type ip = ALB targets pod IPs directly instead of NodePorts.
      # Cheaper (skips a kube-proxy hop) and required for Fargate; fine on EC2 too.
      "alb.ingress.kubernetes.io/target-type" = "ip"

      # Listen on HTTPS:443 only. HTTP:80 could be added if you want redirects.
      "alb.ingress.kubernetes.io/listen-ports" = jsonencode([{ HTTPS = 443 }])

      # Force HTTPS.
      "alb.ingress.kubernetes.io/ssl-redirect" = "443"

      # Backend protocol between ALB and gateway pods is plain HTTP. TLS terminates
      # at the ALB using acm_certificate_arn.
      "alb.ingress.kubernetes.io/backend-protocol" = "HTTP"

      # Health check config — the gateway doesn't have a dedicated /health handler on
      # the NR proprietary port. Accepting 200,404 as healthy prevents endless
      # log spam.
      "alb.ingress.kubernetes.io/healthcheck-port"             = tostring(var.pcg_nr_receiver_port)
      "alb.ingress.kubernetes.io/healthcheck-path"             = "/health"
      "alb.ingress.kubernetes.io/healthcheck-protocol"         = "HTTP"
      "alb.ingress.kubernetes.io/success-codes"                = "200,404"
      "alb.ingress.kubernetes.io/healthcheck-interval-seconds" = "30"

      # TLS certificate ARN — REQUIRED for ALB. AWS ALB does not read K8s TLS
      # Secrets; it needs the cert in ACM referenced by ARN.
      "alb.ingress.kubernetes.io/certificate-arn" = var.acm_certificate_arn
    }
  }

  spec {
    ingress_class_name = "alb"

    tls {
      hosts       = [var.pcg_hostname]
      secret_name = var.tls_secret_name
    }

    rule {
      host = var.pcg_hostname

      http {
        # OTLP HTTP endpoints → gateway:4318
        path {
          path      = "/v1/traces"
          path_type = "Prefix"
          backend {
            service {
              name = var.pcg_service_name
              port { number = var.pcg_otlp_http_port }
            }
          }
        }
        path {
          path      = "/v1/metrics"
          path_type = "Prefix"
          backend {
            service {
              name = var.pcg_service_name
              port { number = var.pcg_otlp_http_port }
            }
          }
        }
        path {
          path      = "/v1/logs"
          path_type = "Prefix"
          backend {
            service {
              name = var.pcg_service_name
              port { number = var.pcg_otlp_http_port }
            }
          }
        }

        # NR proprietary endpoints → gateway:80
        path {
          path      = "/metric/v1"
          path_type = "Prefix"
          backend {
            service {
              name = var.pcg_service_name
              port { number = var.pcg_nr_receiver_port }
            }
          }
        }
        path {
          path      = "/v1/accounts/events"
          path_type = "Prefix"
          backend {
            service {
              name = var.pcg_service_name
              port { number = var.pcg_nr_receiver_port }
            }
          }
        }
        path {
          path      = "/agent_listener"
          path_type = "Prefix"
          backend {
            service {
              name = var.pcg_service_name
              port { number = var.pcg_nr_receiver_port }
            }
          }
        }

        # Catch-all → gateway:80 (NR proprietary)
        path {
          path      = "/"
          path_type = "Prefix"
          backend {
            service {
              name = var.pcg_service_name
              port { number = var.pcg_nr_receiver_port }
            }
          }
        }
      }
    }
  }

  # Note: gRPC (gateway:4317) is NOT included here. AWS ALB gRPC support requires
  # a separate target group + backend-protocol-version annotation, deferred to
  # Kong variant if needed.

  depends_on = [time_sleep.wait_for_pcg]
}

# ALB Controller provisions the AWS ALB asynchronously after the Ingress is
# created. Wait for the ALB to come up before reading its hostname.
# Triggers force re-wait when the Ingress annotations change (e.g., acm_certificate_arn).
resource "time_sleep" "wait_for_alb" {
  count           = var.create_alb_ingress ? 1 : 0
  depends_on      = [kubernetes_ingress_v1.pcg_alb]
  create_duration = var.alb_wait_duration

  triggers = {
    ingress_resource_version = kubernetes_ingress_v1.pcg_alb[0].metadata[0].resource_version
    certificate_arn          = var.acm_certificate_arn
  }
}

# Read the Ingress back to get the ALB hostname that ALB Controller populated.
data "kubernetes_ingress_v1" "pcg_alb" {
  count = var.create_alb_ingress && var.create_route53_record ? 1 : 0

  metadata {
    name      = kubernetes_ingress_v1.pcg_alb[0].metadata[0].name
    namespace = kubernetes_ingress_v1.pcg_alb[0].metadata[0].namespace
  }

  depends_on = [time_sleep.wait_for_alb]
}

# AWS-provided data source: canonical hosted zone ID for ALBs in the current region.
data "aws_elb_hosted_zone_id" "current" {
  count = var.create_route53_record ? 1 : 0
}

# Route53 A-record for the gateway hostname aliased to the ALB.
resource "aws_route53_record" "pcg_alias" {
  count = var.create_route53_record ? 1 : 0

  zone_id = var.route53_zone_id
  name    = var.pcg_hostname
  type    = "A"

  alias {
    name                   = data.kubernetes_ingress_v1.pcg_alb[0].status[0].load_balancer[0].ingress[0].hostname
    zone_id                = data.aws_elb_hosted_zone_id.current[0].id
    evaluate_target_health = true
  }
}
